# Generated by Django 5.1.3 on 2024-11-21 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('area', models.PositiveIntegerField(verbose_name='Kvadrat metri')),
                ('floor', models.CharField(max_length=20, verbose_name='Qavati')),
                ('parking', models.CharField(max_length=50, verbose_name='Avtoturargohi')),
                ('image', models.ImageField(upload_to='homes/images', verbose_name='Rasmi')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yangiliklar yaratilgan vaqti')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Faol emas', 'Faol emas'), ('Faol', 'Faol')], default='Faol emas', max_length=50, verbose_name='holati')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.categorymodel', verbose_name='Kategoriyasi')),
            ],
            options={
                'verbose_name': 'Uy',
                'verbose_name_plural': 'Uylar',
                'db_table': 'houses',
                'ordering': ['-publish_time'],
                'managed': True,
            },
        ),
    ]
