# Generated by Django 5.1.3 on 2024-11-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_housemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
    ]
