# Generated by Django 5.1.3 on 2024-11-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_alter_housemodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='address',
        ),
        migrations.AddField(
            model_name='housemodel',
            name='price_type',
            field=models.CharField(choices=[("so'm", "so'm"), ('₽', '₽'), ('$', '$')], default='$', max_length=10),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
