# Generated by Django 5.1.3 on 2024-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_remove_housemodel_address_housemodel_price_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemodel',
            name='price',
            field=models.IntegerField(verbose_name='Narxi'),
        ),
    ]
