# Generated by Django 5.1.3 on 2024-11-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_alter_housemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
