# Generated by Django 5.0.7 on 2024-11-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0007_alter_housemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='secondary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_category', to='buy.categorymodel', verbose_name='Ikkinchi Kategoriyasi'),
        ),
    ]
