# Generated by Django 5.0.7 on 2024-11-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0008_housemodel_secondary_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('urgency_text', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='housemodel',
            name='secondary_category',
        ),
    ]
